"use client";

import { useCallback, useEffect, useState } from "react";
import { completedLocks, rankTeams, type LockNumber, type Session } from "@/lib/game";
import { Countdown } from "./Countdown";
import { LockProgress } from "./LockProgress";

async function api<T>(url: string, options?: RequestInit): Promise<T> { const response = await fetch(url, { ...options, headers: { "Content-Type": "application/json" } }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "Không thể kết nối máy chủ."); return data; }
const formatTime = (team: { completedAt: Partial<Record<LockNumber, number>> }, startsAt: number | null) => { const time = Math.max(0, ...Object.values(team.completedAt)); if (!time || !startsAt) return "—"; const seconds = Math.max(0, Math.ceil((time - startsAt) / 1000)); return `${String(Math.floor(seconds / 60)).padStart(2, "0")}:${String(seconds % 60).padStart(2, "0")}`; };

export function McDashboard() {
  const [session, setSession] = useState<Session | null>(null);
  const [notice, setNotice] = useState("Tạo một phiên để nhận mã tham gia.");
  const refresh = useCallback(async () => { if (!session) return; try { setSession((await api<{ session: Session }>(`/api/sessions/${session.code}`)).session); } catch (error) { setNotice(error instanceof Error ? error.message : "Không thể làm mới dữ liệu."); } }, [session]);
  useEffect(() => { const poller = window.setInterval(() => void refresh(), 2000); return () => window.clearInterval(poller); }, [refresh]);
  const create = async () => { try { const next = (await api<{ session: Session }>("/api/sessions", { method: "POST" })).session; setSession(next); setNotice("Phiên mới đã sẵn sàng. Chia sẻ mã cho các đội."); } catch (error) { setNotice(error instanceof Error ? error.message : "Không thể tạo phiên."); } };
  const setStatus = async (status: "active" | "announced" | "solutions") => { if (!session) return; try { const next = (await api<{ session: Session }>(`/api/sessions/${session.code}`, { method: "PATCH", body: JSON.stringify({ status }) })).session; setSession(next); setNotice(status === "active" ? "Đồng hồ 5 phút đã bắt đầu." : status === "announced" ? "Đã khóa bài làm và công bố kết quả." : "Đã mở lời giải cho cả lớp."); } catch (error) { setNotice(error instanceof Error ? error.message : "Không thể cập nhật phiên."); } };
  const playerLink = session && typeof window !== "undefined" ? `${window.location.origin}/play?session=${session.code}` : "";
  const teams = session ? rankTeams(session.teams) : [];
  return <main className="mc-shell"><header className="mc-header"><div><p className="eyebrow">BẢNG ĐIỀU KHIỂN MC</p><h1>Ba Khóa<br />Hồ Sơ Kiến Thức</h1></div>{session && <Countdown endsAt={session.endsAt} />}</header>{!session ? <section className="mc-empty"><h2>Sẵn sàng mở hồ sơ?</h2><p>Tạo một phiên mới, sau đó gửi mã hoặc đường dẫn cho các đội.</p><button className="button primary" onClick={create}>Tạo phiên 5 phút</button></section> : <><section className="session-strip"><div><span>MÃ PHIÊN</span><strong>{session.code}</strong></div><div className="link-box"><span>Đường dẫn đội chơi</span><code>{playerLink}</code></div><div className="controls">{session.status === "draft" && <button className="button primary" onClick={() => setStatus("active")}>Bắt đầu 5 phút</button>}{session.status === "active" && <button className="button caution" onClick={() => setStatus("announced")}>Công bố kết quả</button>}{session.status !== "solutions" && <button className="button ghost" onClick={() => setStatus("solutions")}>Mở lời giải</button>}<button className="button ghost" onClick={() => { if (window.confirm("Tạo phiên mới? Dữ liệu phiên hiện tại vẫn được giữ trong Redis.")) void create(); }}>Phiên mới</button></div></section><p className="live-notice" role="status">{notice}</p><section className="score-card"><div className="score-card-head"><div><p className="eyebrow">TIẾN TRÌNH TRỰC TIẾP</p><h2>{teams.length} đội đang tham gia</h2></div><span className={`status-pill ${session.status}`}>{session.status === "draft" ? "Chờ bắt đầu" : session.status === "active" ? "Đang chơi" : session.status === "announced" ? "Đã công bố" : "Đang mở lời giải"}</span></div><div className="table-wrap"><table><thead><tr><th>Hạng</th><th>Đội</th><th>Tiến trình</th><th>Chìa khóa</th><th>Hoàn thành</th><th>Gợi ý</th></tr></thead><tbody>{teams.length ? teams.map((team, index) => <tr key={team.id}><td>{index + 1}</td><th>{team.name}</th><td><LockProgress completed={completedLocks(team)} /></td><td>{completedLocks(team)}/3</td><td>{formatTime(team, session.startsAt)}</td><td>{team.hintCount}</td></tr>) : <tr><td colSpan={6}>Chưa có đội nào tham gia.</td></tr>}</tbody></table></div></section>{session.status === "solutions" && <section className="mc-solution"><p className="eyebrow">KẾT BÀI</p><h2>Hồ sơ đã mở</h2><p>Qua ba khóa, chúng ta vừa ôn lại nguồn gốc và tính chất của tôn giáo, nguyên tắc tôn trọng tự do tín ngưỡng và không tín ngưỡng, cùng tinh thần đại đoàn kết. Khi quay lại tình huống đầu giờ, chúng ta không chỉ đề xuất cách ứng xử mà còn giải thích được cơ sở kiến thức của lựa chọn đó.</p></section>}</>}</main>;
}
